version: '3.8'
services:
  bot:
    build: .
    container_name: discord_bot
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
